language: node_js
node_js:
    node
script: npm run build:prod
deploy:
    local_dir: ./public/
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
        branch: master
