language: node_js

node_js:
    node

script: npm run build:prod

branches:
    only:
        - release

deploy:
    local_dir: ./public/
    skip_cleanup: true
    provider: pages
    github_token: $GITHUB_TOKEN
    target_branch: master
    on:
        branch: release
